### ISSUE TITLE
Importing a mix of types and values in an import using a custom path results in undefined imports in result JavaScript

### ISSUE THREAD

**Issue by booninite** [LeDDGroup/typescript-transform-paths#48]
Given:

file1.ts:
```
export type Foo = 'bar';

export const baz = 'inga'; // ;)
```

file2.ts:
```
import { Foo, baz } from '@custom/scope/file1';

[...]
```

When the code is compiled, the Javascript import will read something like this:

file2.js:
```
import { Foo, baz } from '@custom/scope/file1';
```

but `Foo` will be undefined and cause errors.

**Comment by danielpza** [comment]
Thank you for the bug report, good spot.

**Comment by danielpza** [comment]
Hi @booninite, I've made a PR #53 that should fix this issue, I'll probably merge it and publish it to npm later today.
It seemed to be an issue with the latest versions of typescript, could you confirm this fix it for you?

@all-contributors add @booninite  for bug.

**Comment by booninite** [comment]
@danielpza I wasn't able to pick up the fix today, I should be able to try it out tomorrow and can let you know :+1:

**Comment by laverdet** [comment]
It doesn't seem to be working when I try it. Sample output & configuration is below:

```
marcel@marcel ~/tmp $ cat tsconfig.json 
{
	"compilerOptions": {
		"target": "esnext",
		"lib": [ "esnext" ],

		"baseUrl": ".",
		"paths": {
			"~/*": [ "*" ]
		},

		"plugins": [{ "transform": "typescript-transform-paths" }]
	}
}

marcel@marcel ~/tmp $ cat index.ts 
import { Format, value } from '~/format';
console.log(value);

marcel@marcel ~/tmp $ cat format.ts 
export type Format = number;
export const value = 1;

marcel@marcel ~/tmp $ npx ttsc
marcel@marcel ~/tmp $ cat index.js 
import { Format, value } from "./format";
console.log(value);

marcel@marcel ~/tmp $ cat package.json 
{
  "name": "tmp",
  "dependencies": {
    "ttypescript": "^1.5.10",
    "typescript": "^3.8.3",
    "typescript-transform-paths": "file:../code/typescript-transform-paths"
  }
}

marcel@marcel ~/tmp $ cd ../code/typescript-transform-paths/

marcel@marcel ~/code/typescript-transform-paths $ git rev-parse HEAD
ca44c057f656b3a17c3ad35dc0275def7e0f3515
```

**Comment by DmitryKoterov** [comment]
@danielpza 
Unfortunately PR #53 doesn't help, still the same effect.

Here is a with minimal code which reproduces the issue: https://github.com/DmitryKoterov/typescript-transform-paths-bug - could you please take a look?

Those excess import symbols don't allow to use es6 modules since node complains on an attempt to import an undefined symbol:

![image](https://user-images.githubusercontent.com/65643/80958695-42a89780-8dba-11ea-8ee3-78c38edc8c47.png)
